practica_si_homepage:
    path:     /
    defaults: { _controller: PracticaSIBundle:Default:index }
    
practica_si_login:
    path:     /login
    defaults: { _controller: PracticaSIBundle:Default:login }
    
practica_si_check_login:
    path:     /zona_usuario
    defaults: { _controller: PracticaSIBundle:Default:checkLogin }

practica_si_logout:
    path:     /logout
    defaults: { _controller: PracticaSIBundle:Default:logout }

practica_si_singup:
  path:     /singup
  defaults: { _controller: PracticaSIBundle:Default:singup }

practica_si_new_user:
  path:     /nuevo_usuario
  defaults: { _controller: PracticaSIBundle:Default:newUser }